export const OPEN_FORM_ADD_TASK = 'OPEN_FORM_ADD_TASK';
export const CLOSE_FORM_ADD_TASK = 'CLOSE_FORM_ADD_TASK';

export const GET_LIST_TASK = 'GET_LIST_TASK';
export const GET_LIST_TASK_SUCCESS = 'GET_LIST_TASK_SUCCESS';
export const GET_LIST_TASK_ERROR = 'GET_LIST_TASK_ERROR';
export const RELOAD_LIST_DATA = 'RELOAD_LIST_DATA';
export const LOAD_PAGE = 'LOAD_PAGE';

export const GET_LIST_DATA_SERVICE_TASK = 'GET_LIST_DATA_SERVICE_TASK';
export const GET_LIST_DATA_SERVICE_TASK_SUCCESS = 'GET_LIST_DATA_SERVICE_TASK_SUCCESS';
export const GET_LIST_DATA_SERVICE_TASK_ERROR = 'GET_LIST_DATA_SERVICE_TASK_ERROR';

export const GET_LIST_OPERATION = 'GET_LIST_OPERATION';
export const GET_LIST_OPERATION_SUCCESS = 'GET_LIST_OPERATION_SUCCESS';
export const GET_LIST_OPERATION_ERROR = 'GET_LIST_OPERATION_ERROR';

export const CREATE_TASK = 'CREATE_TASK';
export const CREATE_TASK_SUCCESS = 'CREATE_TASK_SUCCESS';
export const CREATE_TASK_ERROR = 'CREATE_TASK_ERROR';
