export const OPEN_FORM_ADD = 'OPEN_FORM_ADD';
export const CLOSE_FORM_ADD = 'CLOSE_FORM_ADD';
export const CREATE_DATA_SOURCE = 'CREATE_DATA_SOURCE';
export const CHECKING_CONNECTION = 'CHECKING_CONNECTION';
export const DELETE_DATA_SOURCE = 'DELETE_DATA_SOURCE';
export const EDIT_DATA_SOURCE = 'EDIT_DATA_SOURCE';
export const SAVE_EDIT_DATA_SOURCE = 'SAVE_EDIT_DATA_SOURCE';
export const UPDATE_DATA_SOURCE = 'UPDATE_DATA_SOURCE';
export const RESET_DATA_SOURCE = 'RESET_DATA_SOURCE';
export const SET_PAGE_DATA_SOURCE_TABLE = 'SET_PAGE_DATA_SOURCE_TABLE';

export const OPEN_FORM_ADD_QUERY = 'OPEN_FORM_ADD_QUERY';
export const CLOSE_FORM_ADD_QUERY = 'CLOSE_FORM_ADD_QUERY';
export const CREATE_QUERY_PARAM = 'CREATE_QUERY_PARAM';
export const DELETE_QUERY_PARAM = 'DELETE_QUERY_PARAM';
export const EDIT_QUERY_PARAM = 'EDIT_QUERY_PARAM';
export const SAVE_QUERY_PARAM = 'SAVE_QUERY_PARAM';
export const UPDATE_QUERY_PARAM = 'UPDATE_QUERY_PARAM';
export const RESET_QUERY_PARAM = 'RESET_QUERY_PARAM';
export const SET_QUERY_PARAM1 = 'SET_QUERY_PARAM1';
export const SET_PAGE_QUERY_TABLE = 'SET_PAGE_QUERY_TABLE';

export const OPEN_FORM_ADD_RESOURCE = 'OPEN_FORM_ADD_RESOURCE';
export const CLOSE_FORM_ADD_RESOURCE = 'CLOSE_FORM_ADD_RESOURCE';
export const CREATE_RESOURCE = 'CREATE_RESOURCE_DS';
export const DELETE_RESOURCE = 'DELETE_RESOURCE';
export const EDIT_RESOURCE = 'EDIT_RESOURCE';
export const SAVE_RESOURCE = 'SAVE_RESOURCE';
export const UPDATE_DATARESOURCE = 'UPDATE_DATARESOURCE';
export const RESET_RESOURCE = 'RESET_RESOURCE';
export const SET_PAGE_RESOURCE_TABLE = 'SET_PAGE_RESOURCE_TABLE';

export const OPEN_FORM_ADD_OPERATION = 'OPEN_FORM_ADD_OPERATION';
export const CLOSE_FORM_ADD_OPERATION = 'CLOSE_FORM_ADD_OPERATION';
export const CREATE_OPERATION = 'CREATE_OPERATION';
export const DELETE_OPERATION = 'DELETE_OPERATION';
export const EDIT_OPERATION = 'EDIT_OPERATION';
export const SAVE_OPERATION = 'SAVE_OPERATION';
export const UPDATE_OPERATION = 'UPDATE_OPERATION';
export const RESET_OPERATION = 'RESET_OPERATION';
export const SET_PAGE_OPERATION_TABLE = 'SET_PAGE_OPERATION_TABLE';

export const CREATE_DATA_SERVICE = 'CREATE_DATA_SERVICE';
export const CREATE_DATA_SERVICE_SUCCESS = 'CREATE_DATA_SERVICE_SUCCESS';
export const CREATE_DATA_SERVICE_ERROR = 'CREATE_DATA_SERVICE_ERROR';
export const RESET_FORM_DATA_SERVICE = 'RESET_FORM_DATA_SERVICE';
export const GET_DETAIL_DATA_SERVICE_UPDATE = 'GET_DETAIL_DATA_SERVICE_UPDATE';
export const GET_DETAIL_DATA_SERVICE_UPDATE_SUCCESS = 'GET_DETAIL_DATA_SERVICE_UPDATE_SUCCESS';
export const GET_DETAIL_DATA_SERVICE_UPDATE_ERROR = 'GET_DETAIL_DATA_SERVICE_UPDATE_ERROR';

export const UPDATE_DATA_SERVICE = 'UPDATE_DATA_SERVICE';
export const UPDATE_DATA_SERVICE_SUCCESS = 'UPDATE_DATA_SERVICE_SUCCESS';
export const UPDATE_DATA_SERVICE_ERROR = 'UPDATE_DATA_SERVICE_ERROR';

export const RESET_ID_DATA_SERVICE = 'RESET_ID_DATA_SERVICE';

export const LIST_DS_SCREEN = 1;
export const CREATE_DS_SCREEN = 2;
export const UPDATE_DS_SCREEN = 3;
export const DETAIL_DS_SCREEN = 4;

export const RESET_CREATED_STATUS = 'RESET_CREATED_STATUS';
export const SET_SCREEN_NUMBER = 'SET_SCREEN_NUMBER';
export const SET_LOADING = 'SET_LOADING';
