export const FETCH_SYSTEM_INTRO_INFOR = 'FETCH_SYSTEM_INTRO_INFOR';
export const FETCH_SYSTEM_INTRO_INFOR_SUCCESS = 'FETCH_SYSTEM_INTRO_INFOR_SUCCESS';
export const FETCH_SYSTEM_INTRO_INFOR_ERROR = 'FETCH_SYSTEM_INTRO_INFOR_ERROR';
export const CREATE_SYSTEM_INTRO_INFOR = 'CREATE_SYSTEM_INTRO_INFOR';
export const CREATE_SYSTEM_INTRO_INFOR_SUCCESS = 'CREATE_SYSTEM_INTRO_INFOR_SUCCESS';
export const CREATE_SYSTEM_INTRO_INFOR_ERROR = 'CREATE_SYSTEM_INTRO_INFOR_ERROR';
export const UPDATE_SYSTEM_INTRO_INFOR = 'UPDATE_SYSTEM_INTRO_INFOR';
export const UPDATE_SYSTEM_INTRO_INFOR_SUCCESS = 'UPDATE_SYSTEM_INTRO_INFOR_SUCCESS';
export const UPDATE_SYSTEM_INTRO_INFOR_ERROR = 'UPDATE_SYSTEM_INTRO_INFOR_ERROR';
export const DELETE_SYSTEM_INTRO_INFOR = 'DELETE_SYSTEM_INTRO_INFOR';
export const DELETE_SYSTEM_INTRO_INFOR_SUCCESS = 'DELETE_SYSTEM_INTRO_INFOR_SUCCESS';
export const DELETE_SYSTEM_INTRO_INFOR_ERROR = 'DELETE_SYSTEM_INTRO_INFOR_ERROR';
export const SET_ROW_EDITTING = 'SET_ROW_EDITTING';
export const RELOAD_SYSTEM_INTRO_INFOR = 'RELOAD_SYSTEM_INTRO_INFOR';
export const UPDATE_SLIDER_INFOR = 'UPDATE_SLIDER_INFOR';
export const UPDATE_SLIDER_INFOR_SUCCESS = 'UPDATE_SLIDER_INFOR_SUCCESS';
export const UPDATE_SLIDER_INFOR_ERROR = 'UPDATE_SLIDER_INFOR_ERROR';
export const PUBLISH_INTRO_INFOR = 'PUBLISH_INTRO_INFOR';
export const PUBLISH_INTRO_INFOR_SUCCESS = 'PUBLISH_INTRO_INFOR_SUCCESS';
export const PUBLISH_INTRO_INFOR_ERROR = 'PUBLISH_INTRO_INFOR_ERROR';
export const UPDATE_ADDRESS_INFOR = 'UPDATE_ADDRESS_INFOR';
export const UPDATE_ADDRESS_INFOR_SUCCESS = 'UPDATE_ADDRESS_INFOR_SUCCESS';
export const UPDATE_ADDRESS_INFOR_ERROR = 'UPDATE_ADDRESS_INFOR_ERROR';
export const DELETE_INTRO_INFOR = 'DELETE_INTRO_INFOR';
export const DELETE_INTRO_INFOR_SUCCESS = 'DELETE_INTRO_INFOR_SUCCESS';
export const DELETE_INTRO_INFOR_ERROR = 'DELETE_INTRO_INFOR_ERROR';

//Data
export const GET_SYSTEM_INTRO = 'GET_SYSTEM_INTRO';
export const GET_SYSTEM_INTRO_SUCCESS = 'GET_SYSTEM_INTRO_SUCCESS';
export const GET_SYSTEM_INTRO_ERROR = ' GET_SYSTEM_INTRO_ERROR';
export const RELOAD_DATA = 'RELOAD_DATA';
//Create
export const SHOW_CREATE = 'SHOW_CREATE';
export const CREATE_CONTENT = 'CREATE_CONTENT';
export const CREATE_CONTENT_SUCCESS = 'CREATE_CONTENT_SUCCESS';
export const CREATE_CONTENT_ERROR = 'CREATE_CONTENT_ERROR';
//Update
export const SHOW_DATA = 'SHOW_DATA';
export const UPDATE_CONTENT = 'UPDATE_CONTENT';
export const UPDATE_CONTENT_SUCCESS = 'UPDATE_CONTENT_SUCCESS';
export const UPDATE_CONTENT_ERROR = 'UPDATE_CONTENT_ERROR';
export const RELOAD_DATA_CONTENT = 'RELOAD_DATA_CONTENT';
// Delete
export const DELETE_INFOR = 'DELETE_INFOR';
export const DELETE_INFOR_SUCCESS = 'DELETE_INFOR_SUCCESS';
export const DELETE_INFOR_ERROR = 'DELETE_INFOR_ERROR';
export const SHOW_DELETE_CONFIRM = 'SHOW_DELETE_CONFIRM';
export const RELOAD_INFOR = 'RELOAD_INFOR';

//Detail
export const DETAIL_INFOR = 'DETAIL_INFOR';
export const DETAIL_INFOR_SUCCESS = ' DETAIL_INFOR_SUCCESS';
export const DETAIL_INFOR_ERROR = 'DETAIL_INFOR_ERROR';
export const RELOAD_DATA_DETAIL = 'RELOAD_DATA_DETAIL';

//Public
export const PUBLIC_INFOR = 'PUBLIC_INFOR';
export const PUBLIC_INFOR_SUCCESS = 'PUBLIC_INFOR_SUCCESS';
export const PUBLIC_INFOR_ERROR = 'PUBLIC_INFOR_ERROR';
export const RELOAD_DATA_PUBLIC = 'RELOAD_DATA_PUBLIC';
