export const GET_ALL_API_RESOURCE = 'GET_ALL_API_RESOURCE';
export const GET_ALL_API_RESOURCE_SUCCESS = 'GET_ALL_API_RESOURCE_SUCCESS';
export const GET_ALL_API_RESOURCE_ERROR = 'GET_ALL_API_RESOURCE_ERROR';
export const RELOAD_API_RESOURCE = 'RELOAD_API_RESOURCE';

export const UPDATE_API_RESOURCE = 'UPDATE_API_RESOURCE';
export const UPDATE_API_RESOURCE_SUCCESS = 'UPDATE_API_RESOURCE_SUCCESS';
export const UPDATE_API_RESOURCE_ERROR = 'UPDATE_API_RESOURCE_ERROR';

export const INIT_API_RESOURCE_DATA = 'INIT_API_RESOURCE_DATA';
export const CHANGE_API_POLICY_TYPE = 'CHANGE_API_POLICY_TYPE';
export const ADD_NEW_API_RESOURCE = 'ADD_API_NEW_RESOURCE';
export const DELETE_API_RESOURCE = 'DELETE_API_RESOURCE';
export const ADD_PARAMETER_TO_RESOURCE = 'ADD_PARAMETER_TO_RESOURCE';
export const DELETE_PARAMETER_FROM_RESOURCE = 'DELETE_PARAMETER_FROM_RESOURCE';
export const ADD_RESPONSE_TO_RESOURCE = 'ADD_RESPONSE_TO_RESOURCE';
export const DELETE_RESPONSE_FROM_RESOURCE = 'DELETE_RESPONSE_FROM_RESOURCE';
export const CHANGE_DESCRIPTION_RESOURCE = 'CHANGE_DESCRIPTION_RESOURCE';
export const CHANGE_POLICY_RESOURCE = 'CHANGE_POLICY_RESOURCE';

export const UPDATE_PARAMETER_TO_RESOURCE = 'UPDATE_PARAMETER_TO_RESOURCE';
export const UPDATE_RESPONSE_TO_RESOURCE = 'UPDATE_RESPONSE_TO_RESOURCE';

export const UPDATE_PARAMETER_IN_RESOURCE = 'UPDATE_PARAMETER_IN_RESOURCE';
export const UPDATE_RESPONSE_IN_RESOURCE = 'UPDATE_RESPONSE_IN_RESOURCE';

export const SHOW_UPDATE_PARAMETER_FORM = 'SHOW_UPDATE_PARAMETER_FORM';
export const SHOW_UPDATE_RESPONSE_FORM = 'SHOW_UPDATE_RESPONSE_FORM';
