
export const GET_API_DOCUMENT = 'GET_API_DOCUMENT'
export const GET_API_DOCUMENT_SUCCESS = 'GET_API_DOCUMENT_SUCCESS'
export const GET_API_DOCUMENT_ERROR = 'GET_API_DOCUMENT_ERROR'
export const RELOAD_API_DOCUMENT_DATA = 'RELOAD_API_DOCUMENT_DATA'

export const SHOW_CREATE_API_DOCUMENT_FORM = 'SHOW_CREATE_API_DOCUMENT_FORM'
export const CREATE_API_DOCUMENT = 'CREATE_API_DOCUMENT'
export const CREATE_API_DOCUMENT_SUCCESS = 'CREATE_API_DOCUMENT_SUCCESS'
export const CREATE_API_DOCUMENT_ERROR = 'CREATE_API_DOCUMENT_ERROR'

export const SHOW_UPDATE_API_DOCUMENT_FORM = 'SHOW_UPDATE_API_DOCUMENT_FORM'
export const UPDATE_API_DOCUMENT = 'UPDATE_API_DOCUMENT'
export const UPDATE_API_DOCUMENT_SUCCESS = 'UPDATE_API_DOCUMENT_SUCCESS'
export const UPDATE_API_DOCUMENT_ERROR = 'UPDATE_API_DOCUMENT_ERROR'

export const SHOW_DELETE_API_DOCUMENT_CONFIRM = 'SHOW_DELETE_API_DOCUMENT_CONFIRM'
export const DELETE_API_DOCUMENT = 'DELETE_API_DOCUMENT'
export const DELETE_API_DOCUMENT_SUCCESS = 'DELETE_API_DOCUMENT_SUCCESS'
export const DELETE_API_DOCUMENT_ERROR = 'DELETE_API_DOCUMENT_ERROR'
