export const GET_LIST_DATA_SERVICE = 'GET_LIST_DATA_SERVICE';
export const GET_LIST_DATA_SERVICE_SUCCESS = 'GET_LIST_DATA_SERVICE_SUCCESS';
export const GET_LIST_DATA_SERVICE_ERROR = 'GET_LIST_DATA_SERVICE_ERROR';
export const RELOAD_LIST_DATA = 'RELOAD_LIST_DATA';

export const CLICK_DELETE_BUTTON = 'DELETE_DATA_SERVICE';
export const DELETE_DATA_SERVICE = 'DELETE_DATA_SERVICE';
export const DELETE_DATA_SERVICE_SUCCESS = 'DELETE_DATA_SERVICE_SUCCESS';
export const DELETE_DATA_SERVICE_ERROR = 'DELETE_DATA_SERVICE_ERROR';
export const SHOW_DELETE_CONFIRM = 'SHOW_DELETE_CONFIRM';
export const RELOAD_DATA_DATA_SERVICE = 'RELOAD_DATA_DATA_SERVICE';
