export const GET_LIST_SERVICE_ACCESS = 'GET_LIST_SERVICE_ACCESS';
export const GET_LIST_SERVICE_ACCESS_SUCCESS = 'GET_LIST_SERVICE_ACCESS_SUCCESS';
export const GET_LIST_SERVICE_ACCESS_ERROR = 'GET_LIST_SERVICE_ACCESS_ERROR';

export const GET_PERMISSION_LIST_ACCESS_LIMIT = 'GET_PERMISSION_LIST_ACCESS_LIMIT';
export const GET_PERMISSION_LIST_ACCESS_LIMIT_SUCCESS = 'GET_PERMISSION_LIST_ACCESS_LIMIT_SUCCESS';
export const GET_PERMISSION_LIST_ACCESS_LIMIT_ERROR = 'GET_PERMISSION_LIST_ACCESS_LIMIT_ERROR';

export const CREATE_SERVICE_ACCESS = 'CREATE_SERVICE_ACCESS';
export const CREATE_SERVICE_ACCESS_SUCCESS = 'CREATE_SERVICE_ACCESS_SUCCESS';
export const CREATE_SERVICE_ACCESS_ERROR = 'CREATE_SERVICE_ACCESS_ERROR';

export const DELETE_SERVICE_ACCESS = 'DELETE_SERVICE_ACCESS';
export const DELETE_SERVICE_ACCESS_SUCCESS = 'DELETE_SERVICE_ACCESS_SUCCESS';
export const DELETE_SERVICE_ACCESS_ERROR = 'DELETE_SERVICE_ACCESS_ERROR';

export const UPDATE_SERVICE_ACCESS = 'UPDATE_SERVICE_ACCESS';
export const UPDATE_SERVICE_ACCESS_SUCCESS = 'UPDATE_SERVICE_ACCESS_SUCCESS';
export const UPDATE_SERVICE_ACCESS_ERROR = 'UPDATE_SERVICE_ACCESS_ERROR';
