export const GET_ALL_DATAS = 'GET_ALL_DATAS';
export const GET_ALL_DATAS_SUCCESS = 'GET_ALL_DATAS_SUCCESS';
export const GET_ALL_DATAS_ERROR = 'GET_ALL_DATAS_ERROR';
export const RELOAD_DATA = 'RELOAD_DATA';

export const GET_ORGANIZATION = 'GET_ORGANIZATION';
export const GET_ORGANIZATION_SUCCESS = 'GET_ORGANIZATION_SUCCESS';
export const GET_ORGANIZATION_ERROR = 'GET_ORGANIZATION_ERROR';
export const RELOAD_DATA_ORGANIZATION = 'RELOAD_DATA_ORGANIZATION';

export const GET_CATEGORY = 'GET_CATEGORY';
export const GET_CATEGORY_SUCCESS = 'GET_CATEGORY_SUCCESS';
export const GET_CATEGORY_ERROR = 'GET_CATEGORY_ERROR';
export const RELOAD_DATA_CATEGORY = 'RELOAD_DATA_CATEGORY';
