export const GET_GROUP_API_DETAIL = 'GET_GROUP_API_DETAIL';
export const GET_GROUP_API_DETAIL_SUCCESS = 'GET_GROUP_API_DETAIL_SUCCESS';
export const GET_GROUP_API_DETAIL_ERROR = 'GET_GROUP_API_DETAIL_ERROR';
export const CHANGE_STATUS_API = 'CHANGE_STATUS_API';
