export const GET_GROUP_API_CONFIG = 'GET_GROUP_API_CONFIG';

export const GET_API_DEFINITION = 'GET_API_DEFINITION';
export const GET_API_DEFINITION_SUCCESS = 'GET_API_DEFINITION_SUCCESS';
export const GET_API_DEFINITION_ERROR = 'GET_API_DEFINITION_ERROR';
