export const GET_CACHING = 'GET_CACHING';
export const GET_CACHING_SUCCESS = 'GET_CACHING_SUCCESS';
export const GET_CACHING_ERROR = 'GET_CACHING_ERROR';
export const RELOAD_DATA = 'RELOAD_DATA';

//Create Caching
export const SHOW_CREATE = 'SHOW_CREATE';
export const CREATE_CACHING = 'CREATE_CACHING';
export const CREATE_CACHING_SUCCESS = 'CREATE_CACHING_SUCCESS';
export const CREATE_CACHING_ERROR = 'CREATE_CACHING_ERROR';
