//GET_DATA
export const GET_GATEWAY = 'GET_GATEWAY';
export const GET_GATEWAY_SUCCESS = 'GET_GATEWAY_SUCCESS';
export const GET_GATEWAY_ERROR = 'GET_GATEWAY_ERROR';
export const RELOAD_DATA_GATEWAY = 'RELOAD_DATA_GATEWAY';
export const LOAD_PAGE = 'LOAD_PAGE';

//DELETE
export const DELETE_GATEWAY = 'DELETE_GATEWAY';
export const DELETE_GATEWAY_SUCCESS = 'DELETE_GATEWAY_SUCCESS';
export const DELETE_GATEWAY_ERROR = 'DELETE_GATEWAY_ERROR';
export const SHOW_DELETE_CONFIRM = 'SHOW_DELETE_CONFIRM';
export const RELOAD_DATA = 'RELOAD_DATA';

//CREATE
export const SHOW_CREATE = 'SHOW_CREATE';
export const CREATE_GATEWAY = 'CREATE_GATEWAY';
export const CREATE_GATEWAY_SUCCESS = 'CREATE_GATEWAY_SUCCESS';
export const CREATE_GATEWAY_ERROR = 'CREATE_GATEWAY_ERROR';

//UPDATE
export const SHOW_UPDATE_GATEWAY_FORM = 'SHOW_UPDATE_GATEWAY_FORM';
export const UPDATE_GATEWAY = 'UPDATE_GATEWAY';
export const UPDATE_GATEWAY_SUCCESS = 'UPDATE_GATEWAY_SUCCESS';
export const UPDATE_GATEWAY_ERROR = 'UPDATE_GATEWAY_ERROR';
