export const GET_INFORMATION = 'GET_INFORMATION';
export const GET_INFORMATION_SUCCESS = 'GET_INFORMATION_SUCCESS';
export const GET_INFORMATION_ERROR = 'GET_INFORMATION_ERROR';
export const RELOAD_DATA_INFORMATION = 'RELOAD_DATA_INFORMATION';

export const GET_DOCUMENT = 'GET_DOCUMENT';
export const GET_DOCUMENT_SUCCESS = 'GET_DOCUMENT_SUCCESS';
export const GET_DOCUMENT_ERROR = 'GET_DOCUMENT_ERROR';
export const RELOAD_DATA_DOCUMENT = 'RELOAD_DATA_DOCUMENT';

export const GET_PRODUCTION = 'GET_PRODUCTION';
export const GET_PRODUCTION_SUCCESS = 'GET_PRODUCTION_SUCCESS';
export const GET_PRODUCTION_ERROR = 'GET_PRODUCTION_ERROR';
export const RELOAD_DATA_PRODUCTION = 'RELOAD_DATA_PRODUCTION';

export const GET_TEST = 'GET_TEST';
export const GET_TEST_SUCCESS = 'GET_TEST_SUCCESS';
export const GET_TEST_ERROR = 'GET_TEST_ERROR';
export const RELOAD_DATA_TEST = 'RELOAD_DATA_TEST';

export const GET_TOKEN = 'GET_TOKEN';
export const GET_TOKEN_SUCCESS = 'GET_TOKEN_SUCCESS';
export const GET_TOKEN_ERROR = 'GET_TOKEN_ERROR';
export const RELOAD_DATA_TOKEN = 'RELOAD_DATA_TOKEN';

export const GET_SANDBOX = 'GET_SANDBOX';
export const GET_SANDBOX_SUCCESS = 'GET_SANDBOX_SUCCESS';
export const GET_SANDBOX_ERROR = 'GET_SANDBOX_ERROR';
export const RELOAD_DATA_SANDBOX = 'RELOAD_DATA_SANDBOX';

//Đăng kí
export const SUB_REGISTER = 'SUB_REGISTER';
export const SUB_REGISTER_SUCCESS = 'SUB_REGISTER_SUCCESS';
export const SUB_REGISTER_ERROR = 'SUB_REGISTER_ERROR';
export const RELOAD_SUB = 'RELOAD_SUB';
//Hủy đăng kí
export const SUB_UNREGISTER = 'SUB_UNREGISTER';
export const SUB_UNREGISTER_SUCCESS = 'SUB_UNREGISTER_SUCCESS';
export const SUB_UNREGISTER_ERROR = 'SUB_UNREGISTER_ERROR';
export const RELOAD_SUB_UNREGISTER = 'RELOAD_SUB_UNREGISTER';

//Detail Document
export const SHOW_DETAIL_DOCUMENT_FORM = 'SHOW_DETAIL_DOCUMENT_FORM';
export const DETAIL_DOCUMENT = 'DETAIL_DOCUMENT';
export const DETAIL_DOCUMENT_SUCCESS = 'DETAIL_DOCUMENT_SUCCESS';
export const DETAIL_DOCUMENT_ERROR = 'DETAIL_DOCUMENT_ERROR';

//UpdateProduction
export const SHOW_DATA = 'SHOW_DATA';
export const UPDATE_PRODUCTION = 'UPDATE_PRODUCTION';
export const UPDATE_PRODUCTION_SUCCESS = 'UPDATE_PRODUCTION_SUCCESS';
export const UPDATE_PRODUCTION_ERROR = 'UPDATE_PRODUCTION_ERROR';
export const RELOAD_UPDATE_PRODUCTION = 'RELOAD_UPDATE_PRODUCTION';

//UpdateTest
export const SHOW_DATA_TEST = 'SHOW_DATA_TEST';
export const UPDATE_TEST = 'UPDATE_TEST';
export const UPDATE_TEST_SUCCESS = 'UPDATE_TEST_SUCCESS';
export const UPDATE_TEST_ERROR = 'UPDATE_TEST_ERROR';
export const RELOAD_UPDATE_TEST = 'RELOAD_UPDATE_TEST';
