export const GET_API_ENDPOINT_CONFIGURATION= 'GET_API_ENDPOINT_CONFIGURATION';
export const GET_API_ENDPOINT_CONFIGURATION_SUCCESS = 'GET_API_ENDPOINT_CONFIGURATION_SUCCESS';
export const GET_API_ENDPOINT_CONFIGURATION_ERROR = 'GET_API_ENDPOINT_CONFIGURATION_ERROR';
export const RELOAD_API_ENDPOINT_CONFIGURATION = 'RELOAD_API_ENDPOINT_CONFIGURATION';

export const INIT_DEFAULT_DATA = 'INIT_DEFAULT_DATA'
export const SET_PRODUCTION_ACTIVE = 'SET_PRODUCTION_ACTIVE'
export const SET_SANDBOX_ACTIVE = 'SET_SANDBOX_ACTIVE'
export const CHANGE_API_ENDPOINT_TYPE = 'CHANGE_API_ENDPOINT_TYPE';
export const CHANGE_PRODUCTION_ENDPOINT = 'CHANGE_PRODUCTION_ENDPOINT'
export const CHANGE_SANDBOX_ENDPOINT = 'CHANGE_SANDBOX_ENDPOINT'
export const CHANGE_PRODUCTION_SECURITY = 'CHANGE_PRODUCTION_SECURITY'
export const CHANGE_SANDBOX_SECURITY = 'CHANGE_SANDBOX_SECURITY'
export const UPDATE_LOAD_BALANCER_CONFIGURATION = 'UPDATE_LOAD_BALANCER_CONFIGURATION'
export const UPDATE_API_ENDPOINT_CONFIGURATION= 'UPDATE_API_ENDPOINT_CONFIGURATION';
export const UPDATE_API_ENDPOINT_CONFIGURATION_SUCCESS = 'UPDATE_API_ENDPOINT_CONFIGURATION_SUCCESS';
export const UPDATE_API_ENDPOINT_CONFIGURATION_ERROR = 'UPDATE_API_ENDPOINT_CONFIGURATION_ERROR';
export const CLICK_UPDATE_ENDPOINT_CONFIGURATION = 'CLICK_UPDATE_ENDPOINT_CONFIGURATION';

export const SHOW_SECURITY_FORM = 'SHOW_SECURITY_FORM'
export const SHOW_LOAD_BALANCE_FORM = 'SHOW_LOAD_BALANCE_FORM'

export const INIT_ENDPOINT_DATA_LIST = "INIT_ENDPOINT_DATA_LIST"
export const ADD_PRODUCTION_ENDPOINT = "ADD_PRODUCTION_ENDPOINT"
export const REMOVE_PRODUCTION_ENDPOINT = "REMOVE_PRODUCTION_ENDPOINT"
export const ADD_SANDBOX_ENDPOINT = "ADD_SANDBOX_ENDPOINT"
export const REMOVE_SAND_BOX_ENDPOINT = "REMOVE_SAND_BOX_ENDPOINT"
export const CHANGE_LOAD_BALANCER_ENDPOINT_LIST = "CHANGE_LOAD_BALANCER_ENDPOINT_LIST"
export const CHANGE_FAIL_OVER_ENDPOINT_LIST = "CHANGE_FAIL_OVER_ENDPOINT_LIST"
export const CHANGE_HTTP_ENDPOINT_LIST = "CHANGE_HTTP_ENDPOINT_LIST"

export const INIT_DATA = 'INIT_DATA'
export const SET_PRODUCTION = 'SET_PRODUCTION'
export const SET_SANDBOX = 'SET_SANDBOX'
export const CHANGE_ENDPOINT_TYPE = 'CHANGE_ENDPOINT_TYPE';
export const CHANGE_PRODUCTION = 'CHANGE_PRODUCTION'
export const CHANGE_SANDBOX = 'CHANGE_SANDBOX'
export const CHECK_PRODUCTION_SECURITY = 'CHECK_PRODUCTION_SECURITY'
export const CHECK_SANDBOX_SECURITY = 'CHECK_SANDBOX_SECURITY'
export const CHECK_LOAD_BALANCER_CONFIGURATION = 'CHECK_LOAD_BALANCER_CONFIGURATION'
export const CHECK_API_ENDPOINT_CONFIGURATION= 'CHECK_API_ENDPOINT_CONFIGURATION';
export const CHECK_API_ENDPOINT_CONFIGURATION_SUCCESS = 'CHECK_API_ENDPOINT_CONFIGURATION_SUCCESS';
export const CHECK_API_ENDPOINT_CONFIGURATION_ERROR = 'CHECK_API_ENDPOINT_CONFIGURATION_ERROR';
