export const GET_ALL_DATA_SERVICE = 'GET_ALL_DATA_SERVICE';
export const GET_ALL_DATA_SERVICE_SUCCESS = 'GET_ALL_DATA_SERVICE_SUCCESS';
export const GET_ALL_DATA_SERVICE_ERROR = 'GET_ALL_DATA_SERVICE_ERROR';
export const RELOAD_DATA_DATA_SERVICE = 'RELOAD_DATA_DATA_SERVICE';

export const SHOW_CREATE_DATA_SERVICE_FORM = 'SHOW_CREATE_DATA_SERVICE_FORM';
export const CREATE_DATA_SERVICE = 'CREATE_DATA_SERVICE';
export const CREATE_DATA_SERVICE_SUCCESS = 'CREATE_DATA_SERVICE_SUCCESS';
export const CREATE_DATA_SERVICE_ERROR = 'CREATE_DATA_SERVICE_ERROR';

export const SHOW_UPDATE_DATA_SERVICE_FORM = 'SHOW_UPDATE_DATA_SERVICE_FORM';
export const UPDATE_DATA_SERVICE = 'UPDATE_DATA_SERVICE';
export const UPDATE_DATA_SERVICE_SUCCESS = 'UPDATE_DATA_SERVICE_SUCCESS';
export const UPDATE_DATA_SERVICE_ERROR = 'UPDATE_DATA_SERVICE_ERROR';

export const CLICK_DELETE_DATA_SERVICE_BUTTON = 'CLICK_DELETE_DATA_SERVICE_BUTTON';
export const SHOW_DELETE_DATA_SERVICE_CONFIRM = 'SHOW_DELETE_DATA_SERVICE_CONFIRM';
export const DELETE_DATA_SERVICE = 'DELETE_DATA_SERVICE';
export const DELETE_DATA_SERVICE_SUCCESS = 'DELETE_DATA_SERVICE_SUCCESS';
export const DELETE_DATA_SERVICE_ERROR = 'DELETE_DATA_SERVICE_ERROR';

export const GET_SINGLE_DATA_SERVICE = 'GET_SINGLE_DATA_SERVICE';
export const GET_SINGLE_DATA_SERVICE_SUCCESS = 'GET_SINGLE_DATA_SERVICE_SUCCESS';
export const GET_SINGLE_DATA_SERVICE_ERROR = 'GET_SINGLE_DATA_SERVICE_ERROR';

export const SET_FORM_DATA_SERVICE = 'SET_FORM_DATA_SERVICE';
export const RESET_FORM_DATA_SERVICE = 'RESET_FORM_DATA_SERVICE';

///////Create approve /////////////

export const GET_APPROVE = 'GET_APPROVE';
export const GET_APPROVE_SUCCESS = 'GET_APPROVE_SUCCESS';
export const GET_APPROVE_ERROR = 'GET_APPROVE_ERROR';
export const RELOAD_DATA = 'RELOAD_DATA';

////////Create reject ////////

export const SHOW_REQUEST_REJECT_FORM = 'SHOW_REJECT_FORM';
export const REQUEST_REJECT = 'REQUEST_REJECT';
export const REQUEST_REJECT_SUCCESS = 'REQUEST_REJECT_SUCCESS';
export const REQUEST_REJECT_ERROR = 'REQUEST_REJECT_ERROR';
export const LOGIC_REJECT = 'LOGIC_REJECT';
