export const DATA_GENERAL = 'DATA_GENERAL';
export const DATA_GENERAL_SUCCESS = 'DATA_GENERAL_SUCCESS';
export const DATA_GENERAL_ERROR = 'DATA_GENERAL_ERROR';
export const RELOAD_DATA_GENERAL = 'RELOAD_DATA_GENERAL';
