export const GET_SERVICE = 'GET_SERVICE';
export const GET_SERVICE_SUCCESS = 'GET_SERVICE_SUCCESS';
export const GET_SERVICE_ERROR = 'GET_SERVICE_ERROR';
export const RELOAD_DATA = 'RELOAD_DATA';
export const LOAD_PAGE = 'LOAD_PAGE';

//CreateService
export const SHOW_CREATE = 'SHOW_CREATE';
export const CREATE_SERVICE = 'CREATE_SERVICE';
export const CREATE_SERVICE_SUCCESS = 'CREATE_SERVICE_SUCCESS';
export const CREATE_SERVICE_ERROR = 'CREATE_SERVICE_ERROR';

//DeteleService
export const DELETE_SERVICE = 'DELETE_SERVICE_PUBLIC';
export const DELETE_SERVICE_SUCCESS = 'DELETE_SERVICE_PUBLIC_SUCCESS';
export const DELETE_SERVICE_ERROR = 'DELETE_SERVICE_PUBLIC_ERROR';
export const SHOW_DELETE_CONFIRM = 'SHOW_DELETE_CONFIRM';
export const RELOAD_DATE_SERVICE_PUBLIC = 'RELOAD_DATE_SERVICE_PUBLIC';

//Update
export const SHOW_UPDATE_SERVICE_FORM = 'SHOW_UPDATE_SERVICE_FORM';
export const UPDATE_SERVICE = 'UPDATE_SERVICE';
export const UPDATE_SERVICE_SUCCESS = 'UPDATE_SERVICE_SUCCESS';
export const UPDATE_SERVICE_ERROR = 'UPDATE_SERVICE_ERROR';
