export const GET_DATA_DRIVER = 'GET_DATA_DRIVER';
export const GET_DATA_DRIVER_SUCCESS = ' GET_DATA_DRIVER_SUCCESS';
export const GET_DATA_DRIVER_ERROR = 'GET_DATA_DRIVER_ERROR';
export const RELOAD_DATA_DRIVER = 'RELOAD_DATA_DRIVER';
export const LOAD_PAGE = 'LOAD_PAGE';

//Create
export const SHOW_CREATE_DRIVER = 'SHOW_CREATE_DRIVER';
export const CREATE_DRIVER = 'CREATE_DRIVER';
export const CREATE_DRIVER_SUCCESS = 'CREATE_DRIVER_SUCCESS';
export const CREATE_DRIVER_ERROR = 'CREATE_DRIVER_ERROR';

//Delete
export const DELETE_DATA_DRIVER = 'DELETE_DATA_DRIVER';
export const DELETE_DRIVER_SUCCESS = 'DELETE_DRIVER_SUCCESS';
export const DELETE_DRIVER_ERROR = 'DELETE_DRIVER_ERROR';
export const SHOW_DRIVER_CONFIRM = 'SHOW_DRIVER_CONFIRM';
export const RELOAD_DRIVER = 'RELOAD_DRIVER';

//Update
export const SHOW_UPDATE_DRIVER_FORM = 'SHOW_UPDATE_DRIVER_FORM';
export const UPDATE_DRIVER = 'UPDATE_DRIVER';
export const UPDATE_DRIVER_SUCCESS = 'UPDATE_DRIVER_SUCCESS';
export const UPDATE_DRIVER_ERROR = 'UPDATE_DRIVER_ERROR';
