export const GET_API_GENERAL_INFORMATION= 'GET_API_GENERAL_INFORMATION';
export const GET_API_GENERAL_INFORMATION_SUCCESS = 'GET_API_GENERAL_INFORMATION_SUCCESS';
export const GET_API_GENERAL_INFORMATION_ERROR = 'GET_API_GENERAL_INFORMATION_ERROR';
export const RELOAD_API_GENERAL_INFORMATION = 'RELOAD_API_GENERAL_INFORMATION';

export const UPDATE_API_GENERAL_INFORMATION= 'UPDATE_API_GENERAL_INFORMATION';
export const UPDATE_API_GENERAL_INFORMATION_SUCCESS = 'UPDATE_API_GENERAL_INFORMATION_SUCCESS';
export const UPDATE_API_GENERAL_INFORMATION_ERROR = 'UPDATE_API_GENERAL_INFORMATION_ERROR';
