export const GET_CONTENT_FOOTER_PAGE = 'GET_CONTENT_FOOTER_PAGE';
export const GET_CONTENT_FOOTER_PAGE_SUCCESS = 'GET_CONTENT_FOOTER_PAGE_SUCCESS';
export const GET_CONTENT_FOOTER_PAGE_ERROR = 'GET_CONTENT_FOOTER_PAGE_ERROR';

export const GET_CONTENT_HOME_PAGE = 'GET_CONTENT_HOME_PAGE';
export const GET_CONTENT_HOME_PAGE_SUCESS = 'GET_CONTENT_HOME_PAGE_SUCESS';
export const GET_CONTENT_HOME_PAGE_ERROR = 'GET_CONTENT_HOME_PAGE_ERROR';



