export const GET_RESOURCE = 'GET_RESOURCE';
export const GET_RESOURCE_SUCCESS = 'GET_RESOURCE_SUCCESS';
export const GET_RESOURCE_ERROR = 'GET_RESOURCE_ERROR';
export const RELOAD_DATA_RESOURCE = 'RELOAD_DATA_RESOURCE';
export const LOAD_PAGE = 'LOAD_PAGE';
//Create
export const SHOW_CREATE = 'SHOW_CREATE';
export const CREATE_RESOURCE = 'CREATE_RESOURCE';
export const CREATE_RESOURCE_SUCCESS = 'CREATE_RESOURCE_SUCCESS';
export const CREATE_RESOURCE_ERROR = 'CREATE_RESOURCE_ERROR';

//Delete
export const DELETE_DATA_RESOURCE = 'DELETE_DATA_RESOURCE';
export const DELETE_RESOURCE_SUCCESS = 'DELETE_RESOURCE_SUCCESS';
export const DELETE_RESOURCE_ERROR = 'DELETE_RESOURCE_ERROR';
export const SHOW_DELETE_CONFIRM = 'SHOW_DELETE_CONFIRM';
export const RELOAD_RESOURCE = 'RELOAD_RESOURCE';

//Update
export const SHOW_UPDATE_RESOURCE_FORM = 'SHOW_UPDATE_RESOURCE_FORM';
export const UPDATE_RESOURCE = 'UPDATE_RESOURCE';
export const UPDATE_RESOURCE_SUCCESS = 'UPDATE_RESOURCE_SUCCESS';
export const UPDATE_RESOURCE_ERROR = 'UPDATE_RESOURCE_ERROR';
