export const GET_DETAIL_DATA_SERVICE = 'GET_DETAIL_DATA_SERVICE';
export const GET_DETAIL_DATA_SERVICE_SUCCESS = 'GET_DETAIL_DATA_SERVICE_SUCCESS';
export const GET_DETAIL_DATA_SERVICE_ERROR = 'GET_DETAIL_DATA_SERVICE_ERROR';
