export const GET_API_POLICY= 'GET_API_POLICY';
export const GET_API_POLICY_SUCCESS = 'GET_API_POLICY_SUCCESS';
export const GET_API_POLICY_ERROR = 'GET_API_POLICY_ERROR';
export const RELOAD_API_POLICY = 'RELOAD_API_POLICY';
export const CHANGE_API_POLICY = 'CHANGE_API_POLICY';

export const UPDATE_API_POLICY= 'UPDATE_API_POLICY';
export const UPDATE_API_POLICY_SUCCESS = 'UPDATE_API_POLICY_SUCCESS';
export const UPDATE_API_POLICY_ERROR = 'UPDATE_API_POLICY_ERROR';

export const GET_API_SUBSCRIPTION_USER = "GET_API_SUBSCRIPTION_USER"
export const GET_API_SUBSCRIPTION_USER_SUCCESS = "GET_API_SUBSCRIPTION_USER_SUCCESS"
export const GET_API_SUBSCRIPTION_USER_ERROR = "GET_API_SUBSCRIPTION_USER_ERROR"
export const RELOAD_API_SUBSCRIPTION_USER = 'RELOAD_API_SUBSCRIPTION_USER';

export const SHOW_UPDATE_SUBSCRIPTION_FORM= 'SHOW_UPDATE_SUBSCRIPTION_FORM';
export const UPDATE_API_POLICY_SUBSCRIPTION= 'UPDATE_API_POLICY_SUBSCRIPTION';
export const UPDATE_API_POLICY_SUBSCRIPTION_SUCCESS = 'UPDATE_API_POLICY_SUBSCRIPTION_SUCCESS';
export const UPDATE_API_POLICY_SUBSCRIPTION_ERROR = 'UPDATE_API_POLICY_SUBSCRIPTION_ERROR';
